INSERT OR REPLACE INTO citation_sources (id,name,category,claim_url,notes,created_at) VALUES
('src_google','Google Business Profile','primary','https://business.google.com/add','Claim/verify your business profile',strftime('%s','now')),
('src_apple','Apple Business Connect','maps','https://businessconnect.apple.com/','Create/claim listings for Apple Maps',strftime('%s','now')),
('src_bing','Bing Places','maps','https://www.bingplaces.com/','Claim/verify your Bing listing',strftime('%s','now')),
('src_yelp','Yelp','primary','https://biz.yelp.com/claim','Claim your Yelp business page',strftime('%s','now')),
('src_facebook','Facebook','social','https://www.facebook.com/pages/create','Create/claim your business page',strftime('%s','now')),
('src_foursquare','Foursquare','directory','https://foursquare.com/','Create/claim listing',strftime('%s','now')),
('src_yellowpages','Yellow Pages','directory','https://www.yellowpages.com/','Directory citation',strftime('%s','now')),
('src_mapquest','MapQuest','directory','https://www.mapquest.com/','Directory/map citation',strftime('%s','now')),
('src_superpages','Superpages','directory','https://www.superpages.com/','Directory citation',strftime('%s','now')),
('src_citysearch','Citysearch / CityGrid','directory','https://www.citysearch.com/','Directory citation',strftime('%s','now')),
('src_manta','Manta','directory','https://www.manta.com/','Directory citation',strftime('%s','now')),
('src_localcom','Local.com','directory','https://www.local.com/','Directory citation',strftime('%s','now')),
('src_chamber','ChamberofCommerce.com','directory','https://www.chamberofcommerce.com/','Chamber directory citation',strftime('%s','now')),
('src_merchantcircle','MerchantCircle','directory','https://www.merchantcircle.com/','Directory citation',strftime('%s','now')),
('src_hotfrog','Hotfrog','directory','https://www.hotfrog.com/','Directory citation',strftime('%s','now')),
('src_brownbook','Brownbook','directory','https://www.brownbook.net/','Directory citation',strftime('%s','now')),
('src_cylex','Cylex','directory','https://www.cylex-usa.com/','Directory citation',strftime('%s','now')),
('src_ezlocal','EZlocal','directory','https://ezlocal.com/','Directory citation',strftime('%s','now')),
('src_opendi','Opendi','directory','https://www.opendi.com/','Directory citation',strftime('%s','now')),
('src_botw','BOTW Local','directory','https://botw.org/','Directory citation',strftime('%s','now')),
('src_alignable','Alignable','social','https://www.alignable.com/','Business network citation',strftime('%s','now')),
('src_nextdoor','Nextdoor','social','https://nextdoor.com/','Neighborhood business profile',strftime('%s','now')),
('src_bbb','BBB','directory','https://www.bbb.org/','Trust directory listing',strftime('%s','now')),
('src_dnb','Dun & Bradstreet','aggregator','https://www.dnb.com/','Business identity citation',strftime('%s','now')),
('src_ang','Angi','directory','https://www.angi.com/','Home services marketplace (if relevant)',strftime('%s','now')),
('src_thumbtack','Thumbtack','directory','https://www.thumbtack.com/','Services marketplace (if relevant)',strftime('%s','now')),
('src_mapstr','Mapstr','directory','https://mapstr.com/','Optional directory citation',strftime('%s','now')),
('src_showmelocal','ShowMeLocal','directory','https://www.showmelocal.com/','Optional directory citation',strftime('%s','now')),
('src_uscity','USCity','directory','https://www.uscity.net/','Optional directory citation',strftime('%s','now'));
